let BUILDING = [
	[{ // north
		name: ["上海市第一百货商店"],
		dist: 0,
		img_name: "diyibaihuo.png", 
		name_pos: [], 
	}, {
		name: ["亨达利钟表"],
		dist: 0,
		img_name: "hendali.png", 
		name_pos: [], 
	}, {
		name: ["泰康"],
		dist: 0,
		img_name: "taikang.png", 
		name_pos: [], 
	}, {
		name: ["茂昌眼镜公司", "老凤祥银楼"],
		dist: 0,
		img_name: "maochang-laofengxiang.png", 
		name_pos: [], 
	}, {
		name: ["得强酒庄", "培罗蒙", "华美大药房"],
		dist: 0,
		img_name: "deqiang-peiluomeng-huamei.png", 
		name_pos: [], 
	}, {
		name: ["上海帐子公司"],
		dist: 0,
		img_name: "zhangzi.png", 
		name_pos: [], 
	}, {
		name: ["上海市第一食品商店"],
		dist: 0,
		img_name: "diyishipin.png", 
		name_pos: [], 
	}, {
		name: ["上海市时装商店/先施大楼"],
		dist: 0,
		img_name: "shizhuangshangdian-xianshi.png", 
		name_pos: [], 
	}, {
		name: ["沈大成", "三洋食品"],
		dist: 0,
		img_name: "shendacheng-sanyang.png", 
		name_pos: [], 
	}, {
		name: ["上海市第一医药商店"],
		dist: 0,
		img_name: "diyiyiyao.png", 
		name_pos: [], 
	}, {
		name: ["中丝亚太商厦"],
		dist: 0,
		img_name: "zhongsiyatai.png", 
		name_pos: [], 
	}, {
		name: ["LILY商务时装"],
		dist: 0,
		img_name: "lilyshangwu.png", 
		name_pos: [], 
	}, {
		name: ["阳光商厦"],
		dist: 0,
		img_name: "yangguangshangsha.png", 
		name_pos: [], 
	}, {
		name: ["上海旅游品商厦"],
		dist: 0,
		img_name: "lvyoupin.png", 
		name_pos: [], 
	}, {
		name: ["Baleno班尼路"],
		dist: 0,
		img_name: "baleno.png", 
		name_pos: [], 
	}, {
		name: ["SAMSUNG"],
		dist: 0,
		img_name: "samsung.png", 
		name_pos: [], 
	}, {
		name: ["真老大房食品有限公司"],
		dist: 0,
		img_name: "zhenlaoda.png", 
		name_pos: [], 
	}, {
		name: ["老凤祥银楼"],
		dist: 0,
		img_name: "laofengxiang2.png", 
		name_pos: [], 
	}, {
		name: ["Nike"],
		dist: 0,
		img_name: "nike.png", 
		name_pos: [], 
	}, {
		name: ["古今"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["上海金波名烟名酒专卖店", "张小泉", "保安坊", "中国工商银行", "ICBC"],
		dist: 0,
		img_name: "jinbo-zhangxiaoquan-baoanfang-gongshang-icbc.png", 
		name_pos: [], 
	}, {
		name: ["老庙黄金银楼"],
		dist: 0,
		img_name: "laomiao.png", 
		name_pos: [], 
	}, {
		name: ["吴良材眼镜/亨得利钟表公司"],
		dist: 0,
		img_name: "wuliangcai-hengdeli.png", 
		name_pos: [], 
	}, {
		name: ["蔡同德堂"],
		dist: 0,
		img_name: "caitongdetang.png", 
		name_pos: [], 
	}, {
		name: ["周大福", "老凤祥"],
		dist: 0,
		img_name: "zhoudafu-laofengxiang.png", 
		name_pos: [], 
	}, {
		name: ["朵云轩"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["邵万生中华老字号"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["明牌珠宝"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["王开照相"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["华联商厦"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["Omega"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["雅戈尔"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, {
		name: ["恒基名人购物中心"],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	},], [{ // south
		name: ["世贸广场"],
		dist: 0,
		img_name: "shimaoguangchang.png", 
		name_pos: [], 
	}, {
		name: ["新雅粤菜馆"],
		dist: 0,
		img_name: "xinyayue.png", 
		name_pos: [], 
	}, {
		name: ["宝大祥青少年儿童购物中心"],
		dist: 0,
		img_name: "baodaxiang.png", 
		name_pos: [], 
	}, {
		name: ["永安百货"],
		dist: 0,
		img_name: "yonganbaihuo.png", 
		name_pos: [], 
	}, {
		name: ["七重天大厦"],
		dist: 0,
		img_name: "qichongtian.png", 
		name_pos: [], 
	}, {
		name: ["世纪广场"],
		dist: 0,
		img_name: "shijiguangchang.png", 
		name_pos: [], 
	}, {
		name: ["上海索菲特海仑宾馆"],
		dist: 0,
		img_name: "hailun.png", 
		name_pos: [], 
	}, {
		name: ["曼克顿广场"],
		dist: 0,
		img_name: "mankedun.png", 
		name_pos: [], 
	}, {
		name: ["上海置地广场"],
		dist: 0,
		img_name: "zhidiguangchang.png", 
		name_pos: [], 
	}, {
		name: ["圣德娜商厦"],
		dist: 0,
		img_name: "shengdena.png", 
		name_pos: [], 
	}, {
		name: ["悦荟mosaic"],
		dist: 0,
		img_name: "mosaic.png", 
		name_pos: [], 
	}, {
		name: ["宏伊国际广场"],
		dist: 0,
		img_name: "hongyi.png", 
		name_pos: [], 
	}, ]
]

/*
[
	[{
		name: ["name"],
		dist: 0,// the distance to the previous building
		img_name: "xxx.png", // do not need to add /img
		name_pos: [0.1, 0.2], // if name length is more than one, look for this term, each name is presented 
	}, {
		name: [""],
		dist: 0,
		img_name: "", 
		name_pos: [], 
	}, ]
]
*/

// 0: north, 1: west, 2: top